# Logging
logging:
  #path: C:\logs
  #file: diezel.log
  level:
    org.springframework: INFO
    net.dzale.diezel: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    #file:

# Spring
spring:
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  thymeleaf:
    cache: false

# Security
management:
  security:
    enabled: false

# Endpoint
server:
  port: 8080

---

spring:
  profiles: prod
