# DEFAULT

# Logging
logging:
  #path: C:\logs
  #file: diezel.log
  level:
    org.springframework: INFO
    net.dzale.diezel: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    #file:

# Spring
spring:
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop # Determines automatic drop of tables (none/update/create/create-drop)
  thymeleaf:
    cache: false

# Security
management:
  security:
    enabled: false

# Endpoint
server:
  port: 8080

---

# PRODUCTION

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/diezel_db
    username: springuser
    password: aspringuserpassword
  jpa:
    hibernate:
      ddl-auto: none # This is the default for MySQL, no change to the database structure
      #ddl-auto: update # Hibernate changes the database according to the given Entity structures
      #ddl-auto: create # Creates the database every time, but don't drop it when close
      #ddl-auto: create-drop # Creates the database then drops it when the SessionFactory closes